version: '3'
services:
  app:
    build: .
    ports:
      - '8080:3000'
    environment:
      - MONGO_URI=mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'